name: ðŸ’š CI

on:
  push:
    branches:
      "**"
  pull_request:
    branches:
      - main

jobs:
  u_test:
    runs-on: ubuntu-latest
    name: ðŸ§ª Run Unit Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run unit tests
        run: poetry run pytest tests/units

  i_test:
    runs-on: ubuntu-latest
    name: ðŸ§ª Run Integration Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run integration tests
        run: poetry run pytest tests/integrations

  format_check:
    runs-on: ubuntu-latest
    name: ðŸŽ¨ Run Code Format Check
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Check code formatting with black
        run: poetry run black --check src
